### ISSUE TITLE
esp32 in voron?

### ISSUE THREAD

**Issue by shellus** [ByteChild/klipper_config#1]
I saw that you posted rail brackets for esp32 at voron users, I'm curious what you did with esp32 combined with voron?

**Comment by shellus** [comment]
What is the difference between using esp32 and using the LED interface on the control board?

**Comment by ByteChild** [comment]
The LED interface on the board can only control 5V LED strips (and you have to use the dcdc booster module IIRC). I had a roll of WS2815 (12V) laying around, which I wanted to use. Besides that, Klipper isnt capable (yet?) to do any lighting effects, which I wanted too. With the ESP I could have both :) 

As of now my printer has a red scanner effect, when its doing the QGL like K.I.T.T. from Knight Rider, a rising sun effect from yellow to red when its heating up, a green "breathe" when its finished and so on.  And I could go totally overkill and control the ESP via iobroker.

**Comment by shellus** [comment]
德国的朋友，感谢您满足了我的好奇心

**Comment by shellus** [comment]
German friend, thank you for satisfying my curiosity
